---
- hosts: cpanel
  no_log: true
  vars:
        ansible_ssh_user: 'root'
        ansible_port: '64000'
        ansible_ssh_private_key_file: "/home/lotus/.ssh/id_rsa_DN"
 #       limit: "2" #minimum want to display in log
  tags:
    - configuration
  gather_facts: no
  
  tasks:
   - name: remove frozen in exim
